export const PATH = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  ADMIN_PAGE: "/admin",
  ADD_POST: "/admin/addPost",
  POSTS_MANAGE: "/admin/management",
  ALL_POSTS: "/all-posts",
  ITEM_POST: "/item-post",
  NOT_FOUND: "/404",
  SEARCH_POST: "/search",
  USER_PROFILE: "/user-profile",
  USER_SETTINGS: "/user-settings",
  RESET_PASSWORD: "/resetpassword/:resetLink",
  SEND_EMAIL: "/send-email",
  CHECK_MAIL_REGISTER: "/check-mail-register",
  CHECK_MAIL_PASSWORD: "/check-mail-password",
  MANAGE_POST: "/manage-post",
  EDIT_POST: "/edit"
}
